### PR TITLE
feat: i18n

### LINKED ISSUE #49: ✨ [Feature]: 请问一下fluent-editor是否支持国际化
### What problem does this feature solve

image
better table 右键如何配置国际化

### What does the proposed API look like

支持国际化

### What is your project name

*

### PR DESCRIPTION
**Pull request by zzxming**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our Commit Message Guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Provide a function called `changelanguage` to switch languages. Switching languages will trigger an event named `'change-language'` in the current editor. Other modules need to listen for events and update rendered elements when switching languages. like: 

```ts
  this.quill.on(CHANGE_LANGUAGE_EVENT, () => {
    this.destroy()
    this.DEFAULT_COLOR_SUBTITLE = this.quill.options.langText['sub-title-bg-color']
    this.setDefaultMenu()
  })
```

Issue Number: close #49 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Release Notes

- **New Features**
  - Added internationalization (i18n) support with new components for language switching and localized text options.
  - Introduced new Vue components for rich text editing, including customizable toolbar options and internationalization settings.

- **Documentation**
  - Enhanced i18n documentation with detailed instructions and examples for language configuration.
  - Updated table module documentation to include new text configuration options.

- **Bug Fixes**
  - Improved clipboard handling and error management for pasted content and images.

- **Refactor**
  - Streamlined language configuration and dynamic language management within the editor.

### CODE REVIEW

**Comment by kagol** [comment]
@zzxming 是否支持动态切换语言呢？

**Comment by zzxming** [comment]
> @zzxming 是否支持动态切换语言呢？

目前是根据 options 进行静态渲染，如果要支持动态切换的话，我感觉可以通过事件触发，但是所有用到i18n的模块都得重新替换元素，我觉得编辑器不大会有语言切换的场景吧

**Comment by kagol** [comment]
> > @zzxming 是否支持动态切换语言呢？
> 
> 目前是根据 options 进行静态渲染，如果要支持动态切换的话，我感觉可以通过事件触发，但是所有用到i18n的模块都得重新替换元素，我觉得编辑器不大会有语言切换的场景吧

@zzxming 就是可能富文本编辑器只是业务页面中的一部分，业务整体切换语言时，富文本编辑器也需要跟着切换，所以需要能够动态切换语言。

**Comment by zzxming** [comment]
> @zzxming 就是可能富文本编辑器只是业务页面中的一部分，业务整体切换语言时，富文本编辑器也需要跟着切换，所以需要能够动态切换语言，可以在 I18N 模块中提供一个 switchLanguage 之类的方法。

提供了函数进行切换。更新了pr说明

**Review by kagol — APPROVED** [review]

**Comment by kagol** [comment]
@zzxming 有个小问题，不配置语言，只不是不应该提示这个，直接使用默认的语言就行，如果配置错了语言才提示。
image

**Comment by zzxming** [comment]
> @zzxming 有个小问题，不配置语言，只不是不应该提示这个，直接使用默认的语言就行，如果配置错了语言才提示。

@kagol 提了新 pr #130  解决这个问题

**Pull request merged**
