### PR TITLE
fix(table): optimize right-click menu in table-operation-menu(#108)

### PR DESCRIPTION
**Pull request by jany55555**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our Commit Message Guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #108

## What is the new behavior?
优化了 table-operation-menu 中的右键菜单。

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Summary by CodeRabbit

- **New Features**
	- Enhanced positioning logic for the table operation menu, improving its display based on window height.
	- Introduced vertical scrolling for the menu when it exceeds the window height.

- **Bug Fixes**
	- Streamlined menu display logic for better performance and usability. 

- **Chores**
	- Removed unnecessary code and comments for a cleaner codebase.

### CODE REVIEW

**Comment by kagol** [comment]
@jany55555 commit 历史有点小问题，不应该带上之前的commit。

先确保本地dev分支和上游dev分支保持一致，然后从本地dev分支拉一个特性分支进行开发，再提交PR，这样就不会出现 commit 历史不对的问题了

image

**Comment by jany55555** [comment]
@kagol 看看现在是否可以吗？还是说需要我新开一个pr,重新提交呢
Snipaste_2024-12-03_16-39-18

**Comment by kagol** [comment]
> @kagol 看看现在是否可以吗？还是说需要我新开一个pr,重新提交呢
> Snipaste_2024-12-03_16-39-18
> 

文件变化那里好了，但是commit历史还是不对，可以基于上游dev最新代码拉分支，然后重新提交一个PR

**Comment by jany55555** [comment]
> > @kagol 看看现在是否可以吗？还是说需要我新开一个pr,重新提交呢
> > Snipaste_2024-12-03_16-39-18
> 
> 文件变化那里好了，但是commit历史还是不对，可以基于上游dev最新代码拉分支，然后重新提交一个PR。如果能提供一个效果图就更好了。
已经重新提交pr了 链接:https://github.com/opentiny/fluent-editor/pull/140 效果图也在那个pr里

**Comment by kagol** [comment]
Duplicate #140

**Pull request closed without merging**
