### PR TITLE
feat(file): support multiple files or multiple images upload

### PR DESCRIPTION
**Pull request by qwangry**
# PR

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our Commit Message Guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #162

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by kagol** [comment]
@qwangry 和 #168 重复了

**Comment by qwangry** [comment]
> @qwangry 和 #168 重复了

刚刚那个合并了，文档有地方没修改，我该怎么提交呀😂

**Comment by kagol** [comment]
> > @qwangry 和 #168 重复了
> 
> 刚刚那个合并了，文档有地方没修改，我该怎么提交呀😂

可以重新拉分支提交一个哈，步骤如下：
1. 切换到 main 分支，拉取上游仓库main分支最新代码并合并到main分支：git pull upstream main
2. 从main分支拉取新分支：git checkout -b xxx
3. 开发完 push 分支：git push origin xxx
4. 提交新的PR

**Comment by qwangry** [comment]
> > > @qwangry 和 #168 重复了
> > 
> > 
> > 刚刚那个合并了，文档有地方没修改，我该怎么提交呀😂
> 
> 可以重新拉分支提交一个哈，步骤如下：
> 
> 1. 切换到 main 分支，拉取上游仓库main分支最新代码并合并到main分支：git pull upstream main
> 2. 从main分支拉取新分支：git checkout -b xxx
> 3. 开发完 push 分支：git push origin xxx
> 4. 提交新的PR



> > > @qwangry 和 #168 重复了
> > 
> > 
> > 刚刚那个合并了，文档有地方没修改，我该怎么提交呀😂
> 
> 可以重新拉分支提交一个哈，步骤如下：
> 
> 1. 切换到 main 分支，拉取上游仓库main分支最新代码并合并到main分支：git pull upstream main
> 2. 从main分支拉取新分支：git checkout -b xxx
> 3. 开发完 push 分支：git push origin xxx
> 4. 提交新的PR

好的

**Pull request closed without merging**
